# Generated by Django 2.0 on 2017-12-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('round', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Literature', (('LA', 'American Literature'), ('LB', 'British Literature'), ('LE', 'European Literature'), ('LW', 'World Literature'), ('LC', 'Classical Literature'), ('LO', 'Other Literature'))), ('History', (('LA', 'American History'), ('LB', 'British History'), ('LE', 'European History'), ('LW', 'World History'), ('LC', 'Classical History'), ('LO', 'Other History'))), ('Science', (('SB', 'Biology'), ('SC', 'Chemistry'), ('SM', 'Math'), ('CS', 'Computer Science'), ('SO', 'Other Science'))), ('Fine Arts', (('FA', 'Auditory Fine Arts'), ('FV', 'Visual Fine Arts'), ('AV', 'Audiovisual Fine Arts'), ('FO', 'Other Fine Arts'))), ('RL', 'Religion'), ('MY', 'Mythology'), ('SS', 'Social Science'), ('GE', 'Geography'), ('CE', 'Current Events'), ('TR', 'Trash'), ('', '----')], max_length=2)),
                ('difficulty', models.CharField(choices=[('M', 'Middle School'), ('H', 'High School'), ('C', 'College'), ('O', 'Open'), ('', '----')], max_length=1)),
                ('q_id', models.PositiveIntegerField(null=True, unique=True)),
                ('intro_text', models.TextField(blank=True)),
                ('questions', models.ManyToManyField(to='data.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tossup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('round', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Literature', (('LA', 'American Literature'), ('LB', 'British Literature'), ('LE', 'European Literature'), ('LW', 'World Literature'), ('LC', 'Classical Literature'), ('LO', 'Other Literature'))), ('History', (('LA', 'American History'), ('LB', 'British History'), ('LE', 'European History'), ('LW', 'World History'), ('LC', 'Classical History'), ('LO', 'Other History'))), ('Science', (('SB', 'Biology'), ('SC', 'Chemistry'), ('SM', 'Math'), ('CS', 'Computer Science'), ('SO', 'Other Science'))), ('Fine Arts', (('FA', 'Auditory Fine Arts'), ('FV', 'Visual Fine Arts'), ('AV', 'Audiovisual Fine Arts'), ('FO', 'Other Fine Arts'))), ('RL', 'Religion'), ('MY', 'Mythology'), ('SS', 'Social Science'), ('GE', 'Geography'), ('CE', 'Current Events'), ('TR', 'Trash'), ('', '----')], max_length=2)),
                ('difficulty', models.CharField(choices=[('M', 'Middle School'), ('H', 'High School'), ('C', 'College'), ('O', 'Open'), ('', '----')], max_length=1)),
                ('q_id', models.PositiveIntegerField(null=True, unique=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
