# Generated by Django 2.0 on 2017-12-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20171225_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='round',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tossup',
            name='round',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
