# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesionAndAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=800)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('subcategory', models.CharField(max_length=20)),
                ('name', models.IntegerField()),
                ('date', models.DateField()),
                ('is_bonus', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='quesionandanswer',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Trivia'),
        ),
    ]
