# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='id',
        ),
        migrations.AddField(
            model_name='trivia',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trivia',
            name='level',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'College'), ('H', 'High School')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='name',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
