# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20160714_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question_text',
            field=models.TextField(max_length=2000),
        ),
    ]
